// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCypHZl4_VciJ0d2pSuWnv57iBJqlSgW-k',
    appId: '1:362497299363:web:a47627e077a8bf04e40016',
    messagingSenderId: '362497299363',
    projectId: 'gps-pet-track3r',
    authDomain: 'gps-pet-track3r.firebaseapp.com',
    storageBucket: 'gps-pet-track3r.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApx9UZBJ5X-C3eL7MsST9N4Cv9EYCV3sY',
    appId: '1:362497299363:android:fd48cdc448488016e40016',
    messagingSenderId: '362497299363',
    projectId: 'gps-pet-track3r',
    storageBucket: 'gps-pet-track3r.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlJiqz5KtFHRPydSFQWqkffTdFzsQlakA',
    appId: '1:362497299363:ios:255c5f5fe084b20de40016',
    messagingSenderId: '362497299363',
    projectId: 'gps-pet-track3r',
    storageBucket: 'gps-pet-track3r.appspot.com',
    iosClientId: '362497299363-ls8eat7u9dlobplrkko2n2ud1pfp9li9.apps.googleusercontent.com',
    iosBundleId: 'com.keystone.gpspettracker',
  );
}
